from __future__ import annotations

from typing import Any, Protocol

from .profile import DomainProfile


class DomainPolicy(Protocol):
    profile: DomainProfile
    scenario: dict[str, Any]
    risk_candidates: dict[str, Any]

    def candidate(self, candidate_id: str, ego_speed_kph: float) -> dict[str, Any]: ...
    def atomic_candidates(self, candidate_id: str, ego_speed_kph: float) -> list[tuple[str, dict[str, Any]]]: ...
    def is_structured_scenario(self, scenario: dict[str, Any]) -> bool: ...
    def severity_decision(self, scenario: dict[str, Any]) -> dict[str, Any] | None: ...
    def exposure_decision(self, scenario: dict[str, Any]) -> dict[str, Any] | None: ...
    def controllability_decision(self, scenario: dict[str, Any]) -> dict[str, Any] | None: ...
