from __future__ import annotations

from pathlib import Path

from hara_agent.contracts import (
    MethodContract, TemplateRoleConfirmation, TemplateRoleContract,
)

from .role_resolver import TemplateRoleClassifier, TemplateRoleResolver
from .scanner import TemplateWorkbookScanner


class TemplateRoleManifestStore:
    """Cache derived role locations by immutable workbook hash.

    A manifest is generated by the system and contains no copied engineering
    rules. A changed workbook hash necessarily uses a different manifest.
    """

    def __init__(self, root: str | Path):
        self.root = Path(root)

    def path_for(self, template_hash: str) -> Path:
        return self.root / f"{template_hash}.template-role.json"

    def load(self, template_hash: str) -> TemplateRoleContract | None:
        path = self.path_for(template_hash)
        if not path.is_file():
            return None
        return TemplateRoleContract.read_json(path, expected_template_hash=template_hash)

    def save(self, contract: TemplateRoleContract) -> Path:
        return contract.write_json(self.path_for(contract.template_hash))


class TemplateRoleCompiler:
    def __init__(
        self,
        *,
        scanner: TemplateWorkbookScanner | None = None,
        classifier: TemplateRoleClassifier | None = None,
        manifest_store: TemplateRoleManifestStore | None = None,
    ):
        self.scanner = scanner or TemplateWorkbookScanner()
        self.resolver = TemplateRoleResolver(classifier)
        self.manifest_store = manifest_store

    def compile(
        self,
        template_path: str | Path,
        *,
        confirmation: TemplateRoleConfirmation | None = None,
        use_manifest: bool = True,
    ) -> TemplateRoleContract:
        snapshot = self.scanner.scan(template_path)
        if use_manifest and confirmation is None and self.manifest_store is not None:
            cached = self.manifest_store.load(snapshot.source_hash)
            if cached is not None:
                return cached
        contract = self.resolver.resolve(snapshot, confirmation=confirmation)
        if self.manifest_store is not None:
            self.manifest_store.save(contract)
        return contract

    def compile_method_foundation(
        self,
        template_path: str | Path,
        *,
        confirmation: TemplateRoleConfirmation | None = None,
        use_manifest: bool = True,
    ) -> MethodContract:
        return MethodContract.from_role_contract(
            self.compile(
                template_path, confirmation=confirmation, use_manifest=use_manifest
            )
        )
